### ISSUE TITLE
the API returns HTTP status code 200 despite an fatal (for the request) error a request

### ISSUE THREAD

**Issue by ghost** [unioslo/tsd-file-api#81]
Discovered this by accident having started a new uploading (new UUID) with a ... chunk `2` (by mistake).

The API returns `200 OK` for a request when the upload directory keyed by the UUID, normally created during a request for chunk `1`, ends up missing, see the following stack trace when an error is raised, in particular the `FileNotFoundError: [Errno 2] No such file or directory: '/tsd/p11/data/durable/file-import/f722ec35-519b-4ee6-b9a5-fd60bc668fbe'` part of it:

(log records are stripped of (leading?) white space by `journald`, apparently, sorry for the mess)

```
python[9556]: [E 210924 15:51:26 api:1377] stream handler failed with:
python[9556]: [E 210924 15:51:26 api:1378] Traceback (most recent call last):
python[9556]: File "/usr/lib/python3.6/site-packages/tsdfileapi/api.py", line 1315, in prepare
python[9556]: self.res_key
python[9556]: File "/usr/lib/python3.6/site-packages/tsdfileapi/resumables.py", line 266, in prepare
python[9556]: chunk_order_correct = self._refuse_upload_if_not_in_sequential_order(work_dir, upload_id, chunk_num)
python[9556]: File "/usr/lib/python3.6/site-packages/tsdfileapi/resumables.py", line 292, in _refuse_upload_if_not_in_sequential_order
python[9556]: full_chunks_on_disk = self._get_full_chunks_on_disk(work_dir, upload_id)
python[9556]: File "/usr/lib/python3.6/site-packages/tsdfileapi/resumables.py", line 549, in _get_full_chunks_on_disk
python[9556]: chunks_on_disk = os.listdir(work_dir + '/' + upload_id)
python[9556]: FileNotFoundError: [Errno 2] No such file or directory: '/tsd/p11/data/durable/file-import/f722ec35-519b-4ee6-b9a5-fd60bc668fbe'
python[9556]: During handling of the above exception, another exception occurred:
python[9556]: Traceback (most recent call last):
python[9556]: File "/usr/lib/python3.6/site-packages/tsdfileapi/api.py", line 1371, in prepare
python[9556]: os.rename(self.path, self.path_part)
python[9556]: TypeError: rename: src should be string, bytes or os.PathLike, not NoneType
python[9556]: [I 210924 15:51:26 web:2246] 200 PATCH /v1/p11/files/stream/p11-armen-24092021-155106-120.webm?chunk=2&id=f722ec35-519b-4ee6-b9a5-fd60bc668fbe (127.0.0.1) 23.72ms
python[9556]: [E 210924 15:51:26 http1connection:67] Uncaught exception
python[9556]: Traceback (most recent call last):
python[9556]: File "/opt/tsd-file-api-venv/virtualenv/lib/python3.6/site-packages/tornado/http1connection.py", line 257, in _read_message
python[9556]: await body_future
python[9556]: File "/opt/tsd-file-api-venv/virtualenv/lib/python3.6/site-packages/tornado/http1connection.py", line 652, in _read_fixed_body
python[9556]: min(self.params.chunk_size, content_length), partial=True
python[9556]: File "/opt/tsd-file-api-venv/virtualenv/lib/python3.6/site-packages/tornado/iostream.py", line 436, in read_bytes
python[9556]: future = self._start_read()
python[9556]: File "/opt/tsd-file-api-venv/virtualenv/lib/python3.6/site-packages/tornado/iostream.py", line 797, in _start_read
python[9556]: self._check_closed()  # Before reading, check that stream is not closed.
python[9556]: File "/opt/tsd-file-api-venv/virtualenv/lib/python3.6/site-packages/tornado/iostream.py", line 1009, in _check_closed
python[9556]: raise StreamClosedError(real_error=self.error)
python[9556]: tornado.iostream.StreamClosedError: Stream is closed
python[9556]: During handling of the above exception, another exception occurred:
python[9556]: Traceback (most recent call last):
python[9556]: File "/opt/tsd-file-api-venv/virtualenv/lib/python3.6/site-packages/tornado/http1connection.py", line 297, in _read_message
python[9556]: delegate.on_connection_close()
python[9556]: File "/opt/tsd-file-api-venv/virtualenv/lib/python3.6/site-packages/tornado/routing.py", line 272, in on_connection_close
python[9556]: self.delegate.on_connection_close()
python[9556]: File "/opt/tsd-file-api-venv/virtualenv/lib/python3.6/site-packages/tornado/web.py", line 2297, in on_connection_close
python[9556]: self.handler.on_connection_close()
python[9556]: File "/usr/lib/python3.6/site-packages/tsdfileapi/api.py", line 2142, in on_connection_close
python[9556]: if not self.target_file.closed:
python[9556]: AttributeError: 'NoneType' object has no attribute 'closed'
```

**Comment by leondutoit** [comment]
Right, https://github.com/unioslo/tsd-file-api/blob/master/tsdfileapi/resumables.py#L549 throws the `FileNotFoundError`, and then the error is not handled correcty...
